### ISSUE TITLE
TODO add inert support

### ISSUE THREAD

**Issue by MelSumner** [MelSumner/ember-a11y-dropdown#3]
- [ ] Add the inert polyfill for focus-trapping
- [ ] make sure it works
- [ ] add instructions to readme

**Comment by MelSumner** [comment]
Decided to use `ember-focus-trap` for now, and it provides the same outcome. #30
